/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TipBox: React.FC = () => {
  return (
    <div className="flex gap-1 justify-center items-center px-2 py-1 w-full text-sm leading-relaxed bg-orange-100 rounded-lg">
      <span className="self-stretch my-auto font-bold text-orange-500">
        Tip
      </span>
      <p className="self-stretch my-auto font-medium text-neutral-700 text-[13px]">
        동료들도 알고 있는{" "}
        <span className="text-orange-500">회사 이메일 계정으로 가입하기</span>를
        추천해
      </p>
    </div>
  );
};

export default TipBox;
