/**
 * This code was generated by Builder.io.
 */
import React from "react";

const UserProfile: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-wrap gap-10 justify-between items-center p-10 w-full bg-orange-100 rounded-2xl max-md:px-5 max-md:max-w-full">
      <div className="flex gap-4 items-center self-stretch my-auto">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6c6f048af86b812ec4e32f2e122c08bb20e5d09de51bbdb61e196485d8e13b58?placeholderIfAbsent=true&apiKey=c782f79884a44197a4566a36aa7a1229"
          alt="User profile"
          className="object-contain shrink-0 self-stretch my-auto aspect-square rounded-[53px] w-[52px]"
        />
        <div className="flex flex-col self-stretch my-auto w-[137px]">
          <div className="text-2xl font-semibold leading-snug text-neutral-900">
            Dahye Kim
          </div>
          <div className="self-start mt-1.5 text-sm font-medium leading-tight text-center text-neutral-400">
            dh.kim@teamsparta.co
          </div>
        </div>
      </div>
      <button className="self-stretch my-auto text-sm font-semibold leading-snug text-center text-gray-500">
        로그아웃
      </button>
    </div>
  );
};

export default UserProfile;
