/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface StatusBadgeProps {
  status: string;
}

export function StatusBadge({ status }: StatusBadgeProps) {
  return (
    <div className="gap-2.5 self-stretch px-2 py-1 text-sm font-semibold text-rose-500 bg-rose-50 rounded-md">
      {status}
    </div>
  );
}
