/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface UserInfoProps {
  sender: string;
  eta: Date;
}

export function UserInfo({ sender, eta }: UserInfoProps) {
  return (
    <div className="flex flex-col">
      <div className="flex gap-1.5 items-center self-start text-base font-semibold whitespace-nowrap text-neutral-700">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c070d49eefafa2ced494c9760ee99f8c9e25411338a6cf46b992949a00a92e87?placeholderIfAbsent=true&apiKey=c782f79884a44197a4566a36aa7a1229"
          className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
          alt=""
        />
        <span className="self-stretch my-auto">{sender}</span>
      </div>
      <div className="flex gap-0.5 items-start mt-1.5 text-sm font-medium text-gray-400">
        <time className="text-sm font-medium text-gray-400">
          {new Date(eta).toLocaleDateString("ko-KR")}
        </time>
        <span>까지 제작</span>
      </div>
    </div>
  );
}
