/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import UserProfile from "../UserProfile/UserProfile";
import TabNavigation from "../TabNavigation/TabNavigation";
import ProjectCard from "../ProjectCard/ProjectCard";
import { PRD } from "@/app/_types/prd.type";

const DetailComponent: React.FC = () => {
  const projects: PRD[] = [
    {
      id: 1,
      send_at: new Date(),
      receiver: "이성은",
      message: "확인 전",
      prd_url: "https://www.google.com",
      checked: false,
      complated: false,
    },
    {
      id: 2,
      send_at: new Date(),
      receiver: "이성은",
      message: "제작 완료",
      prd_url: "https://www.google.com",
      checked: true,
      complated: true,
    },
    {
      id: 3,
      send_at: new Date(),
      receiver: "이성은",
      message: "제작 완료",
      prd_url: "https://www.google.com",
      checked: true,
      complated: false,
    },
    {
      id: 4,
      send_at: new Date(),
      receiver: "이성은",
      message: "제작 완료",
      prd_url: "https://www.google.com",
      checked: true,
      complated: true,
    },
  ];

  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header />
      <main className="flex flex-col self-center px-6 py-20 w-full max-w-[1200px] min-h-[958px] max-md:px-5 max-md:max-w-full gap-[60px]">
        <UserProfile />
        <section className="flex relative flex-col w-full leading-snug max-md:mt-10 max-md:max-w-full">
          <h2 className="z-0 text-3xl font-semibold text-neutral-900">
            내가 받은 기획서
          </h2>
          <div className="flex z-0 flex-col mt-10 w-full max-md:max-w-full">
            <TabNavigation />
            <div className="flex flex-wrap gap-8 items-center mt-8 w-full max-md:max-w-full">
              {projects.map((project) => (
                <ProjectCard key={project.id} {...project} />
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DetailComponent;
