/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="overflow-hidden gap-2.5 self-stretch px-36 py-4 text-2xl font-extrabold leading-snug text-center whitespace-nowrap border-b border-zinc-200 text-neutral-900 max-md:px-5">
      meerkat
    </header>
  );
};

export default Header;
